// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicClubs2,
  DefaultClubs2Props
} from "./plasmic/proliga_clone/PlasmicClubs2";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Clubs2Props extends Omit<DefaultClubs2Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultClubs2Props altogether and have
// total control over the props for your component.
export interface Clubs2Props extends DefaultClubs2Props {}

function Clubs2_(props: Clubs2Props, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicClubs2 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicClubs2 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Clubs2Props here, but feel free
  // to do whatever works for you.

  return <PlasmicClubs2 root={{ ref }} {...props} />;
}

const Clubs2 = React.forwardRef(Clubs2_);
export default Clubs2;
